# El método de los k-means

In [3]:
import numpy as np

In [5]:
data = np.random.random(90).reshape(30,3)
data

array([[7.18272822e-01, 9.28374339e-01, 9.43199472e-01],
       [5.09666514e-01, 4.82635206e-01, 4.77887038e-01],
       [4.30306425e-01, 8.73503394e-01, 6.77773014e-01],
       [2.88467172e-04, 6.13382196e-01, 5.35170051e-01],
       [8.46462925e-01, 2.17742448e-01, 1.75025611e-01],
       [6.61614321e-01, 6.68947185e-01, 7.86627788e-01],
       [8.93563615e-01, 2.14841563e-01, 6.50122516e-01],
       [8.40289748e-01, 4.01675172e-01, 8.39656847e-01],
       [1.82598205e-01, 4.57599213e-01, 3.35222236e-01],
       [3.10585908e-01, 9.80152134e-01, 4.52744635e-01],
       [7.52478387e-01, 3.63675056e-01, 2.69981319e-01],
       [3.68837134e-01, 9.11087261e-01, 2.83713730e-01],
       [9.17595559e-01, 7.30025223e-01, 2.19748631e-01],
       [2.17620954e-01, 8.15036290e-01, 8.55395460e-01],
       [8.96886218e-01, 9.15386858e-01, 1.32620132e-02],
       [9.81633318e-01, 6.42954224e-02, 1.81123241e-02],
       [9.14588457e-01, 1.30744656e-02, 5.05018909e-01],
       [4.10207496e-01, 2.61115

In [7]:
# Recordemos que k-means tiene un problema, y es que hay que decidir cuantos clusters vamos a tener a priori
# Imaginemos que queremos dos clusters
# Escogeremos al azar dos centroides

c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1],data[c2]])
clust_centers

array([[0.84028975, 0.40167517, 0.83965685],
       [0.36883713, 0.91108726, 0.28371373]])

In [8]:
from scipy.cluster.vq import vq

In [9]:
vq(data,clust_centers)

(array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0], dtype=int32),
 array([0.55047363, 0.49102683, 0.40059174, 0.53636434, 0.68964051,
        0.3258394 , 0.2714188 , 0.        , 0.49293963, 0.19166275,
        0.57765479, 0.        , 0.58138697, 0.59909275, 0.59329457,
        0.8992989 , 0.51818274, 0.66974643, 0.64110292, 0.09991158,
        0.77687747, 0.44105708, 0.54968377, 0.69519265, 0.5003465 ,
        0.39261179, 0.8944187 , 0.38142303, 0.50913468, 0.89216043]))

In [10]:
from scipy.cluster.vq import kmeans

In [11]:
kmeans(data, clust_centers) # esto nos entrega la información de los baricentros, el numero al final es la suma
# de los cuadrados de los errores 

(array([[0.80106256, 0.35101822, 0.35114399],
        [0.3664757 , 0.64966313, 0.58050857]]),
 0.3745543037420574)

In [12]:
# k-means funciona muy bien si en lugar de darle un punto de partida, simplemente especificamos el número
# de clusters que queremos y no los centroides

kmeans(data,2)

(array([[0.74313617, 0.24894579, 0.24358689],
        [0.525808  , 0.66431528, 0.61727988]]),
 0.36013950914943177)